"""
Central configuration for the MazF/MazE operon detection pipeline.

All paths are relative to the project root (mazF_analysis/).
"""

import os

# ---------------------------------------------------------------------------
# Project root (one level up from this file)
# ---------------------------------------------------------------------------
PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def rel(*parts):
    """Return an absolute path rooted at PROJECT_ROOT."""
    return os.path.join(PROJECT_ROOT, *parts)


# ---------------------------------------------------------------------------
# Input data paths
# ---------------------------------------------------------------------------
# Per-genome protein FAA files generated by Prodigal (primary location)
FAA_DIR = rel("results", "faa")

# Fallback: per-genome extracted_proteins.faa inside the NCBI data tree
NCBI_DATA_DIR = rel("Bacillota_ref_dataset", "ncbi_dataset", "data")

# Pre-computed DIAMOND blastp results (one TSV per genome)
MATCHES_DIR = rel("results", "matches")

# Reference query FASTA (3 sequences: MazF, MazE, alr)
REFERENCE_FASTA = rel("ref_protein_mazEF.faa")

# Pre-computed InterProScan results (large TSV — hosted on Zenodo)
INTERPROSCAN_TSV = rel("detecting_mazE", "ORF_detection.tsv")

# Pre-computed 16S rRNA sequences with TACATA cutsite counts + taxonomy fallback
CUTSITE_TSV = rel("data", "16s_cutsite.tsv")

# Pre-existing taxonomy table used as a lineage fallback in Step 7
PREEXISTING_TAX = rel("MazF_operons_analysis_taxonomy.csv")

# NCBI assembly metadata (JSON Lines, one record per genome)
ASSEMBLY_METADATA = rel(
    "Bacillota_ref_dataset", "ncbi_dataset", "data", "assembly_data_report.jsonl"
)

# Reference supplementary figure for validation
REFERENCE_SUPFIG = rel(
    "Bacillota_ref_dataset", "ncbi_dataset", "sup_new_fig5.xlsx"
)

# ---------------------------------------------------------------------------
# Output paths  (all written into pipeline_output/)
# ---------------------------------------------------------------------------
OUTPUT_DIR = rel("pipeline_output")

DIAMOND_DB = rel("pipeline_output", "reference_db.dmnd")
OPERON_CSV = rel("pipeline_output", "mazF_operons_analysis.csv")
ADJ_FASTA = rel("pipeline_output", "ORFs_adj_to_MazF.fasta")
COMPLETE_CSV = rel("pipeline_output", "mazF_operons_analysis_complete.csv")
TAXONOMY_CSV = rel("pipeline_output", "MazF_operons_analysis_taxonomy.csv")
OUTPUT_EXCEL = rel("pipeline_output", "sup_new_fig5.xlsx")

# ---------------------------------------------------------------------------
# Reference sequence IDs (Subject_ID values in DIAMOND tabular output)
# ---------------------------------------------------------------------------
MAZF_SUBJECT_ID = "ndoA_NP_388347.1"
MAZE_SUBJECT_ID = "ndoAI_WP_144530614.1"
ALR_SUBJECT_ID  = "alr_WP_003234284.1"

# ---------------------------------------------------------------------------
# DIAMOND parameters
# ---------------------------------------------------------------------------
DIAMOND_EVALUE   = 1e-5
DIAMOND_OUTFMT   = 6      # tabular
DIAMOND_THREADS  = 4      # overridden by --threads CLI flag

# Column names for outfmt 6 output
DIAMOND_COLS = [
    "Query_ID", "Subject_ID", "Identity", "Alignment_length",
    "Mismatches", "Gap_openings",
    "Start_Alignment_Query", "End_Alignment_Query",
    "Start_Alignment_Subject", "End_Alignment_Subject",
    "E_value", "Bit_score",
]

# ---------------------------------------------------------------------------
# InterProScan parameters
# ---------------------------------------------------------------------------
# InterProScan outfmt TSV column names (13 standard columns)
INTERPRO_COLS = [
    "sequence_id", "md5", "sequence_length", "analysis",
    "signature_accession", "signature_description",
    "start", "end", "score", "status", "date",
    "interpro_accession", "interpro_description",
]

# InterPro accessions associated with Ribbon-Helix-Helix motifs
RHH_ACCESSIONS = {
    "IPR000039",          # Arc repressor mutant, Arc-like
    "IPR002145",          # CopG-like
    "IPR011967",          # MetJ/Arc superfamily
    "IPR013321",          # Arc-type helix-turn-helix DNA-binding
    "IPR022789",          # Transcriptional regulator, RHH fold
    "IPR008994",          # DNA-binding HTH domain, type 3
    "IPR035900",          # Ribbon-helix-helix, conserved site
    "G3DSA:1.10.1220.10", # CATH superfamily (RHH)
}

# Accessions that are false positives (e.g., RuvA — unrelated protein)
RHH_FALSE_POSITIVES = {"IPR010994"}

# ---------------------------------------------------------------------------
# Biological thresholds
# ---------------------------------------------------------------------------
MIN_MAZF_LENGTH = 85   # amino acids — filter too-short fragments
MAX_MAZE_LENGTH = 150  # amino acids — real MazE is ~50–80 aa

# ---------------------------------------------------------------------------
# Canonical operon spatial positions (relative to MazF at position 0)
# ---------------------------------------------------------------------------
MAZE_CANONICAL_POSITION = -1   # MazE immediately upstream of MazF
ALR_CANONICAL_POSITION  = -2   # alr two ORFs upstream of MazF

# ---------------------------------------------------------------------------
# Tree & iTOL annotation outputs
# ---------------------------------------------------------------------------
# Bacillota genus-level taxonomy tree (NCBI; flat Newick; bundled in repo)
# Used as the iTOL base tree (all 165 genera, branch lengths = 1)
NCBI_TREE = rel("data", "bacillota_taxonomy_tree_NCBI_flat.tree")

# Full topology tree with __count_ leaf annotations (source for Step 9 pruning)
# Covers all 140 genera including those absent from the NCBI flat tree (e.g. Peptoniphilus)
TREE_TOPOLOGY = rel("data", "MazEFTree_topology.tree")

# Pruned tree (genera with ≥ MIN_GENUS_SIZE genomes)
TREE_FILE = rel("pipeline_output", "MazEFTree_min15.txt")

# Output directory for iTOL annotation text files
ITOL_DIR = rel("pipeline_output", "itol_annotations")

# Minimum number of genomes in a genus to include in the pruned tree
MIN_GENUS_SIZE = 15

# ---------------------------------------------------------------------------
# Zenodo
# ---------------------------------------------------------------------------
ZENODO_RECORD_ID = "19420781"
ZENODO_BASE_URL  = f"https://zenodo.org/records/{ZENODO_RECORD_ID}/files"

# Files available on Zenodo (relative destination paths)
ZENODO_FILES = {
    "extracted_proteins.tar.gz": rel("pipeline_output", "extracted_proteins.tar.gz"),
    "ORF_detection.tsv":         INTERPROSCAN_TSV,
}
